# Site settings
title: DCMetro
email: kcrocken@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A ruby gem providing access to the WMATA Rails API on the command line and in a Ruby on Rails application.
baseurl: "/dcmetro" # the subpath of your site, e.g. /blog/
url: "http://kencrocken.github.io" # the base hostname & protocol for your site
twitter_username: kencrocken
github_username:  kencrocken

# Build settings
markdown: kramdown

highlight: pygments
